clear all 
close all

s = daq.createSession('ni');
s.IsContinuous = false;

s.addAnalogInputChannel('Dev1',0,'IEPE');
s.addAnalogInputChannel('Dev1',1,'IEPE');
% s.addAnalogInputChannel('Dev3',2,'IEPE');
% s.addAnalogInputChannel('Dev3',3,'IEPE');

Connected_Channels = s.Channels;  %fenetre
    
infobox = figure('Units','normalized',...
            'Position',[0.2 0.2 0.4 0.4],...
            'Color',[0.5 0.5 0.5],...
            'HandleVisibility','callback',...
            'Toolbar','none');
        
stringinfo = evalc('Connected_Channels');

info = uicontrol(infobox,...
            'Style', 'text',...
            'Units', 'normalized',...
            'Fontsize',10,'ForegroundColor',[1 1 1],...
            'BackgroundColor',[0 0 0],...
            'FontWeight','normal',...
            'HorizontalAlignment','left',...
            'Position',[0 0 1 1],...
            'String',stringinfo);